### ISSUE TITLE
Don't add escaped pseudoclass selectors unless required

### ISSUE THREAD

**Issue by ffigiel** [svg-sprite/svg-sprite#7]
I don't like how every sprite gets two selectors, even if I don't use pseudoclasses for my images.

``` css
.svg-spr1,
.svg-spr1\:regular {
        background-position: 0 0;
        background-repeat: no-repeat;
        background-image: url(svg/sprite.svg);
}
```

Could you consider adding an option to check if a pseudoclass selector is required before adding one?
